spring:
  application:
    name: spring-security-template
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/bin/springSecurityTemplate
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework: DEBUG
